version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=tw_user
      - POSTGRES_DB=link_manager_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'

  app:
    build: .
    ports:
      - '8000:8000'
    command: >
      sh -c 'python3 ./link_manager/manage.py migrate &&
            python3 ./link_manager/manage.py populate_db &&
            python3 ./link_manager/manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db
  
volumes:
  pg_data:
    driver: local
