# Generated by Django 5.0.4 on 2024-04-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2024-04-19"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="link",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="link",
            name="title",
            field=models.CharField(default="2024-04-19", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="link",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
