# Generated by Django 5.0.4 on 2024-04-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0004_link_image_link_link_type_alter_link_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2024-04-21 21:22"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
